set -g base-index 1
setw -g pane-base-index 1

bind -n C-H resize-pane -L 2
bind -n C-L resize-pane -R 2
bind -n C-J resize-pane -D 2
bind -n C-K resize-pane -U 2

#bind -n C-S-Left swap-window -t -1\; select-window -t -1
#bind -n C-S-Right swap-window -t +1\; select-window -t +1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g @plugin 'khanghh/tmux-dark-plus-theme'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-right ''
